### ISSUE TITLE
onLoad is called to before libraries are loaded

### ISSUE THREAD

**Issue by lehneres** [Carrooi/Js-GoogleMapsLoader#26]
There seems to be a issue when google maps is loaded with libraries. ' onLoad' is fired before those libraries are fetched and evaluated leading to null pointer issues

```javascript
const MapsLoader = require( "google-maps" );
        if (this.props.useHeat)
            MapsLoader.LIBRARIES = ["places", "visualization"];
        MapsLoader.KEY = 'someKey';

        MapsLoader.load( () =>  console.log( "loaded1" ));

        MapsLoader.onLoad( () => {
            console.log( "loaded" );
            this.setState( { mapLoaded: true } )
        } );
```

both, `loaded1`and `loaded2` are logged before the libs are loaded.

Is there the possibility to delay the onLoad event when using libraries and wait for them to load?

My error message is:

```javascript
Unhandled promise rejection TypeError: this.set is not a function
at new Wy (eval at <anonymous> (https://maps.googleapis.com/maps-api-v3/api/js/22/9b/intl/de_ALL/main.js:65:948), <anonymous>:1:143)
    at Map.updateMap (eval at <anonymous> (http://localhost:3000/app.js:2005:3), <anonymous>:365:39)
    at Map.componentDidUpdate (eval at <anonymous> (http://localhost:3000/app.js:2005:3), <anonymous>:496:24)
    at CallbackQueue.assign.notifyAll (eval at <anonymous> (http://localhost:3000/app.js:1249:3), <anonymous>:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (eval at <anonymous> (http://localhost:3000/app.js:3715:3), <anonymous>:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (eval at <anonymous> (http://localhost:3000/app.js:1087:3), <anonymous>:202:25)
    at ReactReconcileTransaction.Mixin.perform (eval at <anonymous> (http://localhost:3000/app.js:1087:3), <anonymous>:149:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (eval at <anonymous> (http://localhost:3000/app.js:1087:3), <anonymous>:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (eval at <anonymous> (http://localhost:3000/app.js:703:3), <anonymous>:86:38)
    at Object.flushBatchedUpdates (eval at <anonymous> (http://localhost:3000/app.js:703:3), <anonymous>:147:19)
````
which is wrapped into an promise, and this promise is quite long, so I have no clue where the concrete error happens....

**Comment by Prinzhorn** [comment]
Cannot confirm. This very reduced demo correctly logs `object`, so the libraries are defined.

```js
var MapsLoader = require("google-maps");

MapsLoader.LIBRARIES = ["places", "visualization"];

MapsLoader.load(function() {
	console.log(typeof google.maps.places);
	console.log(typeof google.maps.visualization);
});
```

Did you try debugging? You can break on caught and uncaught exceptions and then check out where exactly it happened. From the error message for me it sounds more like a context issue, so your `this` is not bound correctly somewhere and the method `set` can't be found.

**Comment by davidkudera** [comment]
Closing for now, feel free to reopen if needed
